### ISSUE TITLE
Clean up result

### ISSUE THREAD

**Issue by automata** [the-grid/gmr-saliency#1]
Now we have the following as result:
```
saliency:
  bounding_rect: <array of arrays as points> box around biggest salient region
  polygon: <array of arrays as points> approximate polygon around biggest salient region
  center: <array as point> center of biggest salient region
  radius: <number> radius of the approx enclosing circle around biggest salient region
```
We should have the following, preserving the original fields for a while:
```
saliency:
  bbox: <array of objects> box around all regions
  confidence: <number> inverse/normalized entropy of saliency map histogram
  regions: <array of objects> [ 
    bbox: <array of objects> box around salient region
    polygon: <array of objects> polygon around salient region
    center: <object> center point of salient region
    radius: <number> radius of the approx enclosing circle around salient region
  ]
```
In this way, we should remove `saliency.bounding_rect`, `saliency.polygon`, `saliency.center` and `saliency.radius` because a `saliency` is composed by many regions. The only information regarding all those regions is the `saliency.bbox` that encloses them. If one wants to draw or use polygon of the saliency, it should iterate over all `saliency.regions`'s bboxes.

We also should have a standard object to bboxes (`{x: ?, y: ?, width: ?, height: ?}`) and points (`{x: ?, y: ?}`).
